### ISSUE TITLE
Docker Bower Install Connection Timed Out

### ISSUE THREAD

**Issue by neurosnap** [dockerfile/nodejs-bower-grunt#2]
bower c3#\*                     ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/masayuki0812/c3.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection timed out

I keep gettings these errors when I build from nodejs-bower-grunt.  I can't fully build the docker image because I'm getting connection timeouts.  My host is ubuntu 14.04, is there a possible networking issue?  It seems like sometimes it will download a bower repo fine but then get stuck on others.

**Comment by neurosnap** [comment]
It looks like this is more an error of my host network connection, which I have never had a problem with my VM.

**Comment by romanostolosh-devpronet** [comment]
Hi neurosnap,

It seems that I'm having the very same issue you've described.
Would you describe the way you have it fixed?

Thanks

**Comment by neurosnap** [comment]
So my main problem was that my host was actually Windows, but I have an Ubuntu guest that I installed docker onto -- so meta.  The issue was that my VirtualBox was not configured correctly and was intermittently dropping the internet connection to my Ubuntu guest.  Once I reinstalled VirtualBox everything started to work properly.

What kind of setup do you have?

**Comment by romanostolosh-devpronet** [comment]
I'm running Ubuntu/Linux
The issue is actually seems to be gone.. Don't know what happened or what was the cause of it.
